### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by CalderWhite** [asdera/Glossary#1]
Hey Andrew, cool project. This is sort of a feature request not related to the project itself, but to the accessibility of the project. I'm not sure if you know, but if you create a new branch named `gh-pages` with the same code and transfer the base branch to said branch, the website will easily be accessible through Github's static hosting. If you do this, it should end up [here](https://asdera.github.io/Glossary).

**Comment by CalderWhite** [comment]
Interesting... The link works on its own. I suppose Github has changed their ways as to automatically, statically host your website. Apologies for the issue. Maybe just link it as the project's website (next to the description).

**Comment by asdera** [comment]
Thanks, I set Github to host from the master branch and it seems to be working fine. I've also added the website link to my description.
